sudo: false
language: haskell
ghc: 7.8
install:
  - cabal sandbox init
  - git clone git://github.com/mikeyhc/mircy.git
  - cabal sandbox add-source mircy
  - cabal install --only-dependencies --enable-tests
